all: hermano signal hermano2

hermano: hermano.c 
	gcc -o hermano hermano.c

hermano2: hermano2.c
	gcc -o hermano2 hermano2.c

signal: signal.c 
	gcc -o signal signal.c 

clean:
	rm -rf hermano signal hermano2